### ISSUE TITLE
other package named listcomp

### ISSUE THREAD

**Issue by dirkschumacher** [DexGroves/listcomp#2]
@DexGroves I uploaded a package recently to CRAN named [`listcomp`](https://github.com/dirkschumacher/listcomp) and after that noticed that there is your package with the same name on Github. Not sure if you ever planned to upload the package to CRAN. I usually try to avoid name conflics, but missed that one. Sorry for the inconvenience.

**Comment by DexGroves** [comment]
Hey, all good here, don't worry about it. It was thoughtful of you to get in touch.

Cool package my friend!
